### ISSUE TITLE
ValueError: could not broadcast input array from shape (164,109,4) into shape (164,109,3)

### ISSUE THREAD

**Issue by SANMUM** [dvlab-research/VFF#12]
Traceback (most recent call last):                                                                                                                                | 413/3712 [06:18<49:02,  1.12it/s, total_it=413]
  File "train.py", line 200, in <module>
    main()
  File "train.py", line 172, in main
    merge_all_iters_to_one_epoch=args.merge_all_iters_to_one_epoch
  File "/hdd/code/VFF/tools/train_utils/train_utils.py", line 93, in train_model
    dataloader_iter=dataloader_iter
  File "/hdd/code/VFF/tools/train_utils/train_utils.py", line 19, in train_one_epoch
    batch = next(dataloader_iter)
  File "/opt/miniconda3/envs/clocs/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/miniconda3/envs/clocs/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/opt/miniconda3/envs/clocs/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/opt/miniconda3/envs/clocs/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/opt/miniconda3/envs/clocs/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/miniconda3/envs/clocs/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/miniconda3/envs/clocs/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/hdd/code/VFF/pcdet/datasets/kitti/kitti_dataset.py", line 425, in __getitem__
    data_dict = self.prepare_data(data_dict=input_dict)
  File "/hdd/zhanglinjie/code/VFF/pcdet/datasets/dataset.py", line 130, in prepare_data
    'gt_boxes_mask': gt_boxes_mask
  File "/hdd/code/VFF/pcdet/datasets/augmentor/data_augmentor.py", line 135, in forward
    data_dict = cur_augmentor(data_dict=data_dict)
  File "/hdd/code/VFF/pcdet/datasets/augmentor/database_sampler.py", line 352, in __call__
    total_valid_sampled_dict)
  File "/hdd/code/VFF/pcdet/datasets/augmentor/database_sampler.py", line 276, in add_sampled_boxes_to_scene
    data_dict = self.copy_paste_to_image(data_dict, gt_crops2d, gt_number, point_idxes)
  File "/hdd/code/VFF/pcdet/datasets/augmentor/database_sampler.py", line 152, in copy_paste_to_image
    image[_box2d[1]:_box2d[3],_box2d[0]:_box2d[2]] = crop_feat[_order]
ValueError: could not broadcast input array from shape (164,109,4) into shape (164,109,3)

**Comment by SANMUM** [comment]
Sorry about that. There's something wrong with my KITTI datasets, which have now been fixed. Thanks for your excellent work!
