### ISSUE TITLE
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

### ISSUE THREAD

**Issue by lrhlrhlrhlrhlrh** [dvlab-research/VFF#19]
I met this problem when I run :"python train.py --cfg_file cfgs/kitti_models/VFF_PVRCNN.yaml",how to solve it?
Traceback (most recent call last):                                                                                                                                                                | 0/1856 [00:00<?, ?it/s]
  File "train.py", line 198, in <module>
    main()
  File "train.py", line 153, in main
    train_model(
  File "/home/yetao123456/LRH/3D_detection/VFF-main/tools/train_utils/train_utils.py", line 86, in train_model
    accumulated_iter = train_one_epoch(
  File "/home/yetao123456/LRH/3D_detection/VFF-main/tools/train_utils/train_utils.py", line 38, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "/home/yetao123456/LRH/3D_detection/VFF-main/pcdet/models/__init__.py", line 44, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/home/yetao123456/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yetao123456/LRH/3D_detection/VFF-main/pcdet/models/detectors/pv_rcnn_fusion.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/home/yetao123456/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yetao123456/LRH/3D_detection/VFF-main/pcdet/models/backbones_3d/vfe/image_point_vfe.py", line 100, in forward
    batch_dict = self.ffn(batch_dict)
  File "/home/yetao123456/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yetao123456/LRH/3D_detection/VFF-main/pcdet/models/backbones_3d/vfe/image_vfe_modules/ffn/pyramid_ffn.py", line 57, in forward
    ifn_result = self.ifn(images)
  File "/home/yetao123456/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yetao123456/LRH/3D_detection/VFF-main/pcdet/models/backbones_3d/vfe/image_vfe_modules/ffn/ifn/seg_template.py", line 123, in forward
    features = self.model.backbone(x)
  File "/home/yetao123456/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yetao123456/anaconda3/envs/pcdet/lib/python3.8/site-packages/torchvision/models/_utils.py", line 62, in forward
    x = module(x)
  File "/home/yetao123456/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yetao123456/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 732, in forward
    world_size = torch.distributed.get_world_size(process_group)
  File "/home/yetao123456/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 845, in get_world_size
    return _get_group_size(group)
  File "/home/yetao123456/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 306, in _get_group_size
    default_pg = _get_default_group()
  File "/home/yetao123456/anaconda3/envs/pcdet/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 410, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

**Comment by MAI-KOKO** [comment]
I have the same problem, have you solved it yet?

**Comment by lrhlrhlrhlrhlrh** [comment]
Not yet.



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 27, 2024 11:15 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dvlab-research/VFF] RuntimeError: Default process group has notbeen initialized, please make sure to call init_process_group. (Issue #19)




 
I have the same problem, have you solved it yet?
