### ISSUE TITLE
The size of tensor a (16000) must match the size of tensor b (2) at non-singleton dimension 1

### ISSUE THREAD

**Issue by wistful-8029** [dvlab-research/VFF#9]
Traceback (most recent call last):
  File "/home/wistful/work/VFF/tools/train.py", line 199, in <module>
    main()
  File "/home/wistful/work/VFF/tools/train.py", line 170, in main
    merge_all_iters_to_one_epoch=args.merge_all_iters_to_one_epoch
  File "/home/wistful/work/VFF/tools/train_utils/train_utils.py", line 93, in train_model
    dataloader_iter=dataloader_iter
  File "/home/wistful/work/VFF/tools/train_utils/train_utils.py", line 38, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "/home/wistful/work/VFF/pcdet/models/__init__.py", line 44, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/home/wistful/.conda/envs/vff/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wistful/work/VFF/pcdet/models/detectors/pv_rcnn_fusion.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/home/wistful/.conda/envs/vff/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wistful/work/VFF/pcdet/models/backbones_3d/vfe/image_point_vfe.py", line 104, in forward
    batch_dict = self.backbone_3d(batch_dict, fuse_func=self.f2v)
  File "/home/wistful/.conda/envs/vff/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wistful/work/VFF/pcdet/models/backbones_3d/spconv_backbone.py", line 511, in forward
    x_conv1, batch_dict = self.fusion(fuse_func, batch_dict, x_conv1, "layer1")
  File "/home/wistful/work/VFF/pcdet/models/backbones_3d/spconv_backbone.py", line 480, in fusion
    layer_name=layer_name)
  File "/home/wistful/.conda/envs/vff/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wistful/work/VFF/pcdet/models/backbones_3d/vfe/image_vfe_modules/f2v/voxel_field_fusion.py", line 164, in forward
    layer_name=layer_name)
  File "/home/wistful/.conda/envs/vff/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wistful/work/VFF/pcdet/models/backbones_3d/vfe/image_vfe_modules/f2v/point_to_image_projection.py", line 163, in forward
    layer_name=layer_name)
  File "/home/wistful/work/VFF/pcdet/models/backbones_3d/vfe/image_vfe_modules/f2v/point_to_image_projection.py", line 115, in transform_grid
    image_grid, image_depths = transform_utils.project_to_image(project=I_C, points=camera_grid, bmm=True)
  File "/home/wistful/work/VFF/pcdet/utils/transform_utils.py", line 46, in project_to_image
    points_depth = points_t[..., -1] - raw_project[..., 2, 3]
RuntimeError: The size of tensor a (16000) must match the size of tensor b (2) at non-singleton dimension 1

It is estimated that the shape is not correct, how to modify it?

**Comment by wistful-8029** [comment]
sorry, I find there is a same question, thank you!

**Comment by unknowone** [comment]
hi, I met this problem, too. can u give me some advice? lots of thanks!

**Comment by wistful-8029** [comment]
I forgot, but I can send you the code I ran successfully. We can also discuss this direction together.
&nbsp;


Wistfully
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yuanyuan ***@***.***&gt;; 
发送时间: 2023年2月12日(星期天) 晚上8:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [dvlab-research/VFF] The size of tensor a (16000) must match the size of tensor b (2) at non-singleton dimension 1 (Issue #9)





 
hi, I met this problem, too. can u give me some advice? lots of thanks!

**Comment by unknowone** [comment]
thanks a lot!
I cannot see your email, here is my email: bupt_xyy@163.com (posted on my github homepage)

**Comment by XxxuLimei** [comment]
Hi there! I've met the same problem, too.
Can you please send me a copy code? My email is xilm631@163.com.
THX!

**Comment by liulin813** [comment]
Hi there! I've met the same problem, too.
Can you please send me a copy code? My email is liulin010811@gmail.com.
THX!
